### ISSUE TITLE
Cannot install Walabot python APIs on Ubuntu 18.04

### ISSUE THREAD

**Issue by myronww** [Walabot-Projects/Walabot-FirstApp#2]
The following command fails to install on ubuntu 18.04

pip install WalabotAPI --no-index --find-links="/usr/share/walabot/python/"

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 9.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('pip==8.1.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==8.1.1' distribution was not found and is required by the application
```

**Comment by porteusconf** [comment]
Here's what worked for me on `5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 ` (YMMV).  
1. Installed newest SDK namely WalabotSDK_2018.08.26_v1.2.2_Linux64.deb as of July 2022 from [https://site.walabot.com/getting-started](https://site.walabot.com/getting-started) which among other things installs `/usr/share/walabot/python/WalabotAPI.py`
2. Try running `walabot-diagnose` to see if you get error shown below. If so,  do steps 3 and 4 to fix it.
```
 $ walabot-diagnose 
walabot-diagnose: error while loading shared libraries: libWalabotAPI.so: cannot open shared object file: No such file or directory
```
3 `sudo nano :/etc/ld.so.conf.d/walabot-sdk.conf` with one line ` /usr/lib/walabot`
4. `sudo ldconfig`
5. `walabot-diagnose` should now launch ok (you may need to run in a new terminal or reboot first):
```
 /usr/bin/walabot-diagnose
Please connect 1 Walabot to your host.
After the tests are done, pleases disconnect your Walabot before continuing.
Press enter to continue ...
```
6. Try the pip install now... hopefully it will work similar to below...
```
$ pip --version
pip 22.0.4 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

$ pip install WalabotAPI --no-index --find-links="/usr/share/walabot/python/"
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/walabot/python/
Processing /usr/share/walabot/python/WalabotAPI-1.2.2.tar.gz
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: WalabotAPI
  Building wheel for WalabotAPI (setup.py) ... done
  Created wheel for WalabotAPI: filename=WalabotAPI-1.2.2-py3-none-any.whl size=8742 sha256=fcc76713ebf11e605835e10b7d4d299d5c43b5dacd788bb2f6beb5b8b3ef4ea6
  Stored in directory: /home/barb/.cache/pip/wheels/cf/d9/bd/29979f6b046865953394aa1c512eca7e6a07450cb894afca6c
Successfully built WalabotAPI
Installing collected packages: WalabotAPI
Successfully installed WalabotAPI-1.2.2

$ ls -l  /home/barb/.cache/pip/wheels/cf/d9/bd/29979f6b046865953394aa1c512eca7e6a07450cb894afca6c
total 12
-rw-r--r-- 1 barb barb 8742 Jul 20 21:13 WalabotAPI-1.2.2-py3-none-any.whl
```
Unzip above file and it contains `WalabotAPI.py` whose first few lines are:
```
from __future__ import unicode_literals
from sys import platform, maxsize
from ctypes import *
from os.path import exists, join
from collections import namedtuple
from struct import calcsize

WALABOT_SUCCESS = 0
WALABOT_ERROR = 1

class WalabotError(Exception):
    """ Walabot's specific Exception object.
        Args:
            message:        Short explanation about the occured exception.
            code:           Code number of the exception.
            extended:       Error information for Vayyar support.
    """
    def __init__(self, message, code):
        super(Exception, self).__init__(message)
        self.code = code

# Make sure python is 64 bits
if (platform == 'win32') and  (8 * calcsize('P') != 64):
...
```
