### ISSUE TITLE
None of the Linux API Samples Work

### ISSUE THREAD

**Issue by GregoryVPerry** [Walabot-Projects/Walabot-FirstApp#3]
Is this product even being maintained anymore? I've attempted to get support from Walabot on a couple of occasions and it took weeks just to get a single one line answer that didn't resolve any of the issues with the Linux API after I spent almost $1,000 on the Creator's Edition product with extended sensors.

After exactly following the install instructions:

```
$ walabot-diagnose
walabot-diagnose: error while loading shared libraries: libWalabotAPI.so: cannot open shared object file: No such file or directory
$ python HelloWalabot.py 
Traceback (most recent call last):
  File "HelloWalabot.py", line 8, in <module>
    wlbt.Initialize()  # set the path to the essetial database files
  File "/home/gperry/.local/lib/python2.7/site-packages/WalabotAPI.py", line 164, in Initialize
    _RaiseIfErr(Initialize.__name__, res)
  File "/home/gperry/.local/lib/python2.7/site-packages/WalabotAPI.py", line 124, in _RaiseIfErr
    raise WalabotError(funcName + ": " + errorMessage, res)
WalabotAPI.WalabotError: Initialize: Internal error: Type 1
```
What are these "essential database files" needed for the package?

**Comment by porteusconf** [comment]
Try my steps 3 and 4 from [issue2](https://github.com/Walabot-Projects/Walabot-HelloWalabot/issues/2#issuecomment-1190945598)   

> 3 `sudo nano :/etc/ld.so.conf.d/walabot-sdk.conf` to contain one line `/usr/lib/walabot`
> 4. `sudo ldconfig`

The .deb that installs sdk forgot to provide a one-line ldconfig config file, so just created it in step 3.

About database files the readme says 

> **`wlbt.wlbt.Initialize()`**
> The Walabot SDK uses certain database files. This function loads the path to those files.
> If no path is specified, the SDK will use the default path and internal databases."
> 

So I am guessing the hello demo should work without you having to explicitly provide any database files. BTW though you asked in 2019, have you since given up?  If so might you still have dev-kit to sell? ;)
