### ISSUE TITLE
Can I use this sample for Vayyar vCube?

### ISSUE THREAD

**Issue by nyxrobotics** [Walabot-Projects/Walabot-FirstApp#4]
Nice to meet you. I would like to use the vCube radar from Vayyar in this program.
But cannot find the device. Will my device not work this way?
```bash
~/lib/Walabot-HelloWalabot$ python HelloWalabot.py 
Traceback (most recent call last):
  File "HelloWalabot.py", line 9, in <module>
    wlbt.ConnectAny()  # establishes communication with the Walabot
  File "/home/nyx/.local/lib/python3.8/site-packages/WalabotAPI.py", line 203, in ConnectAny
    _RaiseIfErr(ConnectAny.__name__, _wlbt.Walabot_ConnectAny())
  File "/home/nyx/.local/lib/python3.8/site-packages/WalabotAPI.py", line 124, in _RaiseIfErr
    raise WalabotError(funcName + ": " + errorMessage, res)
WalabotAPI.WalabotError: ConnectAny: No available devices have been found
```

This is my dmesg shows the device.
```bash
[82215.681414] hub 5-1.4.2:1.0: USB hub found
[82215.681453] hub 5-1.4.2:1.0: 4 ports detected
[82215.729718] usb 4-1.4.2: new high-speed USB device number 16 using xhci_hcd
[82215.835805] usb 4-1.4.2: New USB device found, idVendor=0451, idProduct=8142, bcdDevice= 1.00
[82215.835811] usb 4-1.4.2: New USB device strings: Mfr=0, Product=0, SerialNumber=1
[82215.835813] usb 4-1.4.2: SerialNumber:
[82215.889065] hub 4-1.4.2:1.0: USB hub found
[82215.889279] hub 4-1.4.2:1.0: 4 ports detected
[82216.477664] usb 4-1.4.2.1: new high-speed USB device number 17 using xhci_hcd
[82216.585406] usb 4-1.4.2.1: New USB device found, idVendor=2c9c, idProduct=1000, bcdDevice= 0.00
[82216.585414] usb 4-1.4.2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[82216.585417] usb 4-1.4.2.1: Product: Vayyar USB Device
[82216.585419] usb 4-1.4.2.1: Manufacturer: Vayyar 
[82216.585421] usb 4-1.4.2.1: SerialNumber: vCube_A
[82216.669991] usb 4-1.4.2.4: new high-speed USB device number 18 using xhci_hcd
[82216.772782] usb 4-1.4.2.4: New USB device found, idVendor=2c9c, idProduct=1000, bcdDevice= 0.00
[82216.772789] usb 4-1.4.2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[82216.772791] usb 4-1.4.2.4: Product: Vayyar USB Device
[82216.772794] usb 4-1.4.2.4: Manufacturer: Vayyar 
[82216.772795] usb 4-1.4.2.4: SerialNumber: vCube_B
```

**Comment by nyxrobotics** [comment]
```bash
walabot-diagnose 
Please connect 1 Walabot to your host.
After the tests are done, pleases disconnect your Walabot before continuing.
Press enter to continue ...


Running test ConfigFile - Done
Running test SystemInfo - Done
Running test UsbDevice - Done
Running test ConnectAny - Done
Running test TargetSensor - Done
Running test BreathingSensor - Done
Running test InWallSensor - Done
Running test StressTargetSensor - Done
Running test StressBreathingSensor - Done
Running test StressInWallSensor - Done
Copying files...

Diagnose successful.

summary:

Test Name                     Status    Fail Reason Summery
---------                     ------    -------------------
ConfigFile                    success   
SystemInfo                    success   
UsbDevice                     success   
ConnectAny                    FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624
TargetSensor                  FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624
BreathingSensor               FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624
InWallSensor                  FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624
StressTargetSensor            FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624
StressBreathingSensor         FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624
StressInWallSensor            FAILED    Failed at Walabot_ConnectAny - Internal error: Type 3, code 196624


Diagnose file at: /tmp/vayyar-diagnose.tar.gz


Please disconnect the Walabot now.
Press enter to continue ...
```

**Comment by nyxrobotics** [comment]
`196624` -> `0x30010`
WALABOT_ERR_ARENA_SIZE_TOO_BIG: 0x10
WALABOT_ERR_DB: 0x30000
